/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesListRouteRouteImport } from './routes/venuesListRoute'
import { Route as SpecificVenueRouteRouteImport } from './routes/specificVenueRoute'
import { Route as RegisterRouteRouteImport } from './routes/registerRoute'
import { Route as ProfileRouteRouteImport } from './routes/profileRoute'
import { Route as LoginRouteRouteImport } from './routes/loginRoute'
import { Route as HomeRouteRouteImport } from './routes/homeRoute'
import { Route as EditVenueRouteRouteImport } from './routes/editVenueRoute'
import { Route as CreateVenueRouteRouteImport } from './routes/createVenueRoute'

const VenuesListRouteRoute = VenuesListRouteRouteImport.update({
  id: '/venuesListRoute',
  path: '/venuesListRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecificVenueRouteRoute = SpecificVenueRouteRouteImport.update({
  id: '/specificVenueRoute',
  path: '/specificVenueRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/registerRoute',
  path: '/registerRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profileRoute',
  path: '/profileRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/loginRoute',
  path: '/loginRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/homeRoute',
  path: '/homeRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const EditVenueRouteRoute = EditVenueRouteRouteImport.update({
  id: '/editVenueRoute',
  path: '/editVenueRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateVenueRouteRoute = CreateVenueRouteRouteImport.update({
  id: '/createVenueRoute',
  path: '/createVenueRoute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/createVenueRoute': typeof CreateVenueRouteRoute
  '/editVenueRoute': typeof EditVenueRouteRoute
  '/homeRoute': typeof HomeRouteRoute
  '/loginRoute': typeof LoginRouteRoute
  '/profileRoute': typeof ProfileRouteRoute
  '/registerRoute': typeof RegisterRouteRoute
  '/specificVenueRoute': typeof SpecificVenueRouteRoute
  '/venuesListRoute': typeof VenuesListRouteRoute
}
export interface FileRoutesByTo {
  '/createVenueRoute': typeof CreateVenueRouteRoute
  '/editVenueRoute': typeof EditVenueRouteRoute
  '/homeRoute': typeof HomeRouteRoute
  '/loginRoute': typeof LoginRouteRoute
  '/profileRoute': typeof ProfileRouteRoute
  '/registerRoute': typeof RegisterRouteRoute
  '/specificVenueRoute': typeof SpecificVenueRouteRoute
  '/venuesListRoute': typeof VenuesListRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/createVenueRoute': typeof CreateVenueRouteRoute
  '/editVenueRoute': typeof EditVenueRouteRoute
  '/homeRoute': typeof HomeRouteRoute
  '/loginRoute': typeof LoginRouteRoute
  '/profileRoute': typeof ProfileRouteRoute
  '/registerRoute': typeof RegisterRouteRoute
  '/specificVenueRoute': typeof SpecificVenueRouteRoute
  '/venuesListRoute': typeof VenuesListRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/createVenueRoute'
    | '/editVenueRoute'
    | '/homeRoute'
    | '/loginRoute'
    | '/profileRoute'
    | '/registerRoute'
    | '/specificVenueRoute'
    | '/venuesListRoute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/createVenueRoute'
    | '/editVenueRoute'
    | '/homeRoute'
    | '/loginRoute'
    | '/profileRoute'
    | '/registerRoute'
    | '/specificVenueRoute'
    | '/venuesListRoute'
  id:
    | '__root__'
    | '/createVenueRoute'
    | '/editVenueRoute'
    | '/homeRoute'
    | '/loginRoute'
    | '/profileRoute'
    | '/registerRoute'
    | '/specificVenueRoute'
    | '/venuesListRoute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CreateVenueRouteRoute: typeof CreateVenueRouteRoute
  EditVenueRouteRoute: typeof EditVenueRouteRoute
  HomeRouteRoute: typeof HomeRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  ProfileRouteRoute: typeof ProfileRouteRoute
  RegisterRouteRoute: typeof RegisterRouteRoute
  SpecificVenueRouteRoute: typeof SpecificVenueRouteRoute
  VenuesListRouteRoute: typeof VenuesListRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venuesListRoute': {
      id: '/venuesListRoute'
      path: '/venuesListRoute'
      fullPath: '/venuesListRoute'
      preLoaderRoute: typeof VenuesListRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specificVenueRoute': {
      id: '/specificVenueRoute'
      path: '/specificVenueRoute'
      fullPath: '/specificVenueRoute'
      preLoaderRoute: typeof SpecificVenueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registerRoute': {
      id: '/registerRoute'
      path: '/registerRoute'
      fullPath: '/registerRoute'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profileRoute': {
      id: '/profileRoute'
      path: '/profileRoute'
      fullPath: '/profileRoute'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loginRoute': {
      id: '/loginRoute'
      path: '/loginRoute'
      fullPath: '/loginRoute'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeRoute': {
      id: '/homeRoute'
      path: '/homeRoute'
      fullPath: '/homeRoute'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editVenueRoute': {
      id: '/editVenueRoute'
      path: '/editVenueRoute'
      fullPath: '/editVenueRoute'
      preLoaderRoute: typeof EditVenueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createVenueRoute': {
      id: '/createVenueRoute'
      path: '/createVenueRoute'
      fullPath: '/createVenueRoute'
      preLoaderRoute: typeof CreateVenueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CreateVenueRouteRoute: CreateVenueRouteRoute,
  EditVenueRouteRoute: EditVenueRouteRoute,
  HomeRouteRoute: HomeRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  ProfileRouteRoute: ProfileRouteRoute,
  RegisterRouteRoute: RegisterRouteRoute,
  SpecificVenueRouteRoute: SpecificVenueRouteRoute,
  VenuesListRouteRoute: VenuesListRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
